[pytest]
# AttributeError in pytest with asyncio after include code in fixtures
asyncio_mode = auto

faulthandler_timeout=180
filterwarnings =
    ignore::pydantic.warnings.PydanticDeprecatedSince20:docarray\..*
    ignore:`general_(plain|after)_validator_function` is deprecated.*:DeprecationWarning:docarray\..*
    ignore:`general_(plain|after)_validator_function` is deprecated.*:DeprecationWarning:pydantic_core\.core_schema
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
    timeout: marks test timeout duration
    asyncio: marks that run async tests
    repeat: marks that test run n times
