pipelines:
  - pipeline:
      name: 'default'
      default: true
      device: 'cuda'

      page_classifier:
        - model_name_or_path: 'models/longformer-base-4096'
          task: 'text-extraction'
          name: 'text_extraction'
          enabled: True
          batch_size: 1 # batch size > 1 causes errors due to wrong batch aggregation
          device: 'cuda'
          group: 'group1'

