pipelines:
  - pipeline:
      name: 'default-corr'
      default: True
      device: 'cuda'

      id2label:
        '0': additional_information
        '1': attorney
        '2': auth_approval
        '3': auth_denial
        '4': bankruptcy
        '5': cms_letter
        '6': dispute
        '7': eligibility
        '8': medical_certificate
        '9': medical_record
        '10': misc
        '11': newborn
        '12': noop_blank
        '13': noop_check
        '14': noop_cover
        '15': noop_envelope
        '16': noop_eob
        '17': noop_hicfa
        '18': noop_notice
        '19': noop_patpay
        '20': noop_w9
        '21': pa_162
        '22': referral
        '23': refund_request
        '24': tax_1099


      page_classifier:
        - model_name_or_path: 'marie/lmv3-medical-document-classification'
          type: 'transformers'
          task: 'text-classification-multimodal'
          device: 'cuda'
          enabled: True
          name: 'medical-page-classifier'
          group: 'medical_page_classifier'

        - model_name_or_path: 'rms/corr-layoutlmv3-classifier'
          name: 'corr_page_classifier_layoutlmv3'
          type: 'transformers'
          task: 'text-classification-multimodal'
          device: 'cuda'
          enabled: True
          group: 'corr-classifier'

        - model_name_or_path: 'rms/corr-longformer-classifier'
          task: 'text-classification'
          name: 'corr_page_classifier_longformer'
          type: 'transformers'
          enabled: True
          batch_size: 1 # batch size > 1 causes errors due to wrong batch aggregation
          device: 'cuda'
          group: 'corr-classifier'

      sub_classifier:
        - model_name_or_path: 'rms/corr-auth-longformer-classifier'
          task: 'text-classification'
          name: 'corr_auth_sub_classifier'
          type: 'transformers'
          enabled: True
          batch_size: 1 # batch size > 1 causes errors due to wrong batch aggregation
          device: 'cuda'
          group: 'corr-classifier'

          id2label:
            '0': auth_denial_in
            '1': auth_denial_op

          # Filter should be on the same level as the sub-classifier, for now this is just a global filter
          filter:
            type: 'exact'
            pattern: 'auth_denial'

#      page_indexer:
#        - model_name_or_path: 'rms/corr-indexing-llm/qwen'
#          enabled: True
#          type: 'mmllm'
#          device: 'cuda'
#          name: 'corr-page-indexer-qwen'
#          group: 'corr_indexing_llm'
#
##        - model_name_or_path: 'rms/corr-indexing-llm/qwen-small'
##          enabled: True
##          type: 'mmllm'
##          device: 'cuda'
##          name: 'corr-page-indexer-qwen-small'
##          group: 'corr_indexing_llm'
#
#      llm_tasks:
#        - name: 'corr_patients'
#          group: 'corr_indexing_llm'
#        - name: 'corr_payer'
#          group: 'corr_indexing_llm'