---
- name: Marie-AI - Status Node
  hosts: "{{ target_group }}"
  gather_facts: false


  vars:
    stack_name: "dev"

  tasks:
    # use the default python3 and then we will switch to VENV
    - name: Set the Python interpreter to the virtual environment
      set_fact:
        ansible_python_interpreter: /usr/bin/python3

    - name: Update apt cache
      apt:
        update_cache: yes
      become_user: root
      become: yes
      become_method: sudo

    - name: Ensure curl is installed
      apt:
        name: curl
        state: present
      become_user: root
      become: yes
      become_method: sudo

    - name: Install uv
      shell: curl -LsSf https://astral.sh/uv/install.sh | sh
      args:
        creates: /usr/local/bin/uv
        executable: /bin/bash
      environment:
        UV_INSTALL_DIR: /usr/local/bin
      become_user: root
      become: yes
      become_method: sudo

    - name: Install python3-venv with --fix-missing option
      apt:
        name: python3-venv
        state: present
        update_cache: yes
        force_apt_get: yes
        install_recommends: no
        allow_unauthenticated: yes

      become_user: root
      become: yes
      become_method: sudo

    - name: Create a virtual environment
      command: /usr/local/bin/uv venv --python /usr/bin/python3 /opt/venv
      args:
        creates: /opt/venv/bin/python
      become_user: root
      become: yes
      become_method: sudo

    - name: Install specific version of requests and urllib3 in virtual environment
      command: /usr/local/bin/uv pip install --python /opt/venv/bin/python requests==2.31.0 'urllib3<2.0'
      become_user: root
      become: yes
      become_method: sudo

    - name: Set the Python interpreter to the virtual environment
      set_fact:
        ansible_python_interpreter: /opt/venv/bin/python
