# ############### Marie-AI Extract Executors ###############

# GPU-enabled inference servers for document extraction

services:
  marie-extract-executor:
    image: marieai/marie:${EXTRACT_IMAGE_TAG:-4.0.0-cuda}
    restart: unless-stopped
    container_name: 'marieai-${EXTRACT_STACK_NAME:-dev}-server'
    init: true
    tty: true
    network_mode: host

    command: >
      server --start 
      --uses /etc/marie/config/service/extract/${EXTRACT_CONFIG_TAG:-marie-extract-4.0.0.yml}

    environment:
      - MARIE_CACHE_SKIP_LOAD=true
      - MARIE_DEFAULT_MOUNT=/etc/marie
      - MARIE_LOG_CONFIG=docker
      - MARIE_DEPLOYMENT_NAME=marie
      - COLUMNS=180
      - JINA_MP_START_METHOD=spawn
      - JINA_LOG_LEVEL=${EXTRACT_LOG_LEVEL:-DEBUG}

    volumes:
      - extract_config:/etc/marie/config:ro
      - extract_models:/etc/marie/model_zoo:rw
      - extract_policy:/etc/ImageMagick-6/policy.xml:ro
      - extract_cache:/root/.cache/huggingface/hub:rw

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, utility]
        limits:
          memory: 32G

    logging:
      driver: local
      options:
        max-size: "100m"
        max-file: "10"

    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8080/status', timeout=5)"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 300s

    networks:
      - marie_default

    labels:
      - "marie.service=extract-executor"
      - "marie.version=${EXTRACT_IMAGE_TAG:-4.0.0-cuda}"
      - "marie.gpu=enabled"

volumes:
  extract_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${EXTRACT_CONFIG_PATH:-/mnt/data/marie-ai/config}

  extract_models:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${EXTRACT_MODEL_PATH:-/mnt/data/marie-ai/model_zoo}

  extract_policy:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${EXTRACT_CONFIG_PATH:-/mnt/data/marie-ai/config}/service/im-policy.xml

  extract_cache:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${EXTRACT_CACHE_PATH:-/mnt/data/marie-ai/model_zoo/cache/huggingface/hub}

networks:
  marie_default:
    external: true