# ############### Marie-AI Gateway ###############

# Container networking setup
# docker network create --driver=bridge marie_default

services:
  marie-gateway:
    image: marieai/marie-gateway:${GATEWAY_IMAGE_TAG:-4.0.0-cpu}
    restart: unless-stopped
    container_name: 'marieai-gateway'
    init: true
    tty: true
    network_mode: host

    command: >
      gateway 
      --uses /etc/marie/config/service/extract/${GATEWAY_CONFIG_TAG:-marie-gateway-4.0.0.yml}
      --protocols HTTP GRPC
      --ports 51000 52000
      --extra-search-paths /mnt/data/marie-ai/config/extra_py_modules

    environment:
      - MARIE_CACHE_SKIP_LOAD=true
      - MARIE_DEFAULT_MOUNT=/etc/marie
      - MARIE_LOG_CONFIG=docker
      - MARIE_DEPLOYMENT_NAME=marie
      - COLUMNS=180
      - JINA_MP_START_METHOD=fork
      - JINA_LOG_LEVEL=${GATEWAY_LOG_LEVEL:-DEBUG}

    volumes:
      - gateway_config:/etc/marie/config:ro
      - gateway_models:/etc/marie/model_zoo:rw
      - gateway_policy:/etc/ImageMagick-6/policy.xml:ro

    logging:
      driver: local
      options:
        max-size: "100m"
        max-file: "10"

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:52000/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

    networks:
      - marie_default

    labels:
      - "marie.service=gateway"
      - "marie.version=${GATEWAY_IMAGE_TAG:-4.0.0-cpu}"

volumes:
  gateway_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${GATEWAY_CONFIG_PATH:-/mnt/data/marie-ai/config}

  gateway_models:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${GATEWAY_MODEL_PATH:-/mnt/data/marie-ai/model_zoo}

  gateway_policy:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${GATEWAY_CONFIG_PATH:-/mnt/data/marie-ai/config}/service/im-policy.xml

networks:
  marie_default:
    external: true
