version: "3.9"

# ############### Networks ###############

# Container networking setup
# docker network create --driver=bridge public
# sysctl net.ipv4.conf.all.forwarding=1

# Dashboard accessible via `http://localhost:7777/dashboard/#/'
# Consul accessible via `http://localhost:8500/`

services:
  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    volumes:
     - ./config/prometheus:/etc/prometheus
     - prometheus_data:/prometheus
    command: "--web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus"
    links:
    - alertmanager
    networks:
      - public
    ports:
     - "9090:9090"

  alertmanager:
    image: prom/alertmanager:latest
    restart: unless-stopped
    networks:
      - public
    ports:
      - "9093:9093"
    volumes:
      - "./config/alertmanager:/config"
      - alertmanager_data:/data
    command: --config.file=/config/alertmanager.yml --log.level=debug

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    user: "472"
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ./config/grafana/provisioning/:/etc/grafana/provisioning/
      - grafana_data:/var/lib/grafana
#      - /var/lib/grafana:/var/lib/grafana
    env_file:
      - ./config/grafana/config.monitoring
    links:
      - prometheus
    networks:
      - public

  loki:
    image: grafana/loki:2.7.5
    restart: unless-stopped
    volumes:
      - ./config/grafana/loki:/etc/loki
      - loki_data:/loki
    ports:
      - "3100:3100"
    command: --config.file=/etc/loki/loki-config.yaml
    links:
      - prometheus
      - grafana
    networks:
      - public

  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    container_name: 'marie-rabbitmq'
    ports:
        - 5672:5672 # AMQP
        - 15672:15672 # HTTP
    environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest
        - RABBITMQ_DEFAULT_VHOST=/
    volumes:
        - rabbitmq_data:/var/lib/rabbitmq
        - rabbitmq_log:/var/log/rabbitmq
    networks:
        - public

volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
  loki_data:
    driver: local
  alertmanager_data:
    driver: local
  rabbitmq_data:
    driver: local
  rabbitmq_log:
    driver: local

# ############### Networks ###############
networks:
  public:
    external: true
