# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import warnings

import grpc

from marie.proto import event_stream_pb2 as event__stream__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in event_stream_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EventStreamServiceStub(object):
    """Bidirectional streaming for real-time events"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamEvents = channel.stream_stream(
            '/marieai.events.EventStreamService/StreamEvents',
            request_serializer=event__stream__pb2.ClientMessage.SerializeToString,
            response_deserializer=event__stream__pb2.ServerMessage.FromString,
            _registered_method=True,
        )
        self.GetReplayBuffer = channel.unary_unary(
            '/marieai.events.EventStreamService/GetReplayBuffer',
            request_serializer=event__stream__pb2.ReplayRequest.SerializeToString,
            response_deserializer=event__stream__pb2.ReplayResponse.FromString,
            _registered_method=True,
        )


class EventStreamServiceServicer(object):
    """Bidirectional streaming for real-time events"""

    def StreamEvents(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReplayBuffer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventStreamServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'StreamEvents': grpc.stream_stream_rpc_method_handler(
            servicer.StreamEvents,
            request_deserializer=event__stream__pb2.ClientMessage.FromString,
            response_serializer=event__stream__pb2.ServerMessage.SerializeToString,
        ),
        'GetReplayBuffer': grpc.unary_unary_rpc_method_handler(
            servicer.GetReplayBuffer,
            request_deserializer=event__stream__pb2.ReplayRequest.FromString,
            response_serializer=event__stream__pb2.ReplayResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'marieai.events.EventStreamService', rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        'marieai.events.EventStreamService', rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class EventStreamService(object):
    """Bidirectional streaming for real-time events"""

    @staticmethod
    def StreamEvents(
        request_iterator,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/marieai.events.EventStreamService/StreamEvents',
            event__stream__pb2.ClientMessage.SerializeToString,
            event__stream__pb2.ServerMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetReplayBuffer(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marieai.events.EventStreamService/GetReplayBuffer',
            event__stream__pb2.ReplayRequest.SerializeToString,
            event__stream__pb2.ReplayResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
