{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ferretdb.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ferretdb.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mongodb
      protocol: TCP
      name: mongodb
  selector:
    {{- include "ferretdb.selectorLabels" . | nindent 4 }}
{{- end }}
