enabled: true

image:
  registry: docker.io
  repository: rabbitmq
  tag: "3-management-alpine"
  digest: ""
  pullPolicy: IfNotPresent

auth:
  username: marie
  password: ""
  existingSecret: ""
  existingSecretPasswordKey: rabbitmq-password

service:
  type: ClusterIP
  port: 5672
  managementPort: 15672
  annotations: {}

persistence:
  enabled: true
  storageClass: ""
  size: 8Gi
  accessModes:
    - ReadWriteOnce

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

podSecurityContext:
  fsGroup: 999
  fsGroupChangePolicy: OnRootMismatch

securityContext:
  allowPrivilegeEscalation: false
