{{- if and .Values.enabled .Values.migrations.enabled }}
{{- $schema := .Values.auth.schema | default "marie_scheduler" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgresql.fullname" . }}-migrations
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
data:
  000-prelude.sql: |
    CREATE SCHEMA IF NOT EXISTS {{ $schema }};
    CREATE EXTENSION IF NOT EXISTS pgcrypto;
  {{- range $path, $_ := .Files.Glob "files/schema/*.sql" }}
  {{ base $path }}: |
{{ replace "{schema}" $schema ($.Files.Get $path) | indent 4 }}
  {{- end }}
  {{- range $path, $_ := .Files.Glob "files/schema/lease/*.sql" }}
  lease-{{ base $path }}: |
{{ replace "{schema}" $schema ($.Files.Get $path) | indent 4 }}
  {{- end }}
{{- end }}
