{{- if and .Values.enabled (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.secretName" . }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-password: {{ include "postgresql.postgresPassword" . | quote }}
  password: {{ include "postgresql.password" . | quote }}
{{- end }}
