{{- if and .Values.enabled (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minio.secretName" . }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.auth.rootUserKey }}: {{ .Values.auth.rootUser | quote }}
  {{ .Values.auth.rootPasswordKey }}: {{ .Values.auth.rootPassword | quote }}
  {{- $users := .Values.provisioning.users | default list }}
  {{- if gt (len $users) 0 }}
  {{- $user := index $users 0 }}
  app-user: {{ $user.username | quote }}
  app-password: {{ $user.password | quote }}
  {{- end }}
{{- end }}
