- name: Set etcd name and IP for this node
  set_fact:
    etcd_name: "{{ inventory_hostname }}"
    etcd_ip: "{{ ansible_host }}"

- name: Build initial cluster string from hostvars
  set_fact:
    initial_cluster: >-
      {{ groups['etcd_cluster'] | map('extract', hostvars, 'ansible_host') | zip(groups['etcd_cluster']) |
         map('join', '=http://') | map('regex_replace', '$', ':2380') | join(',') }}

- name: Ensure Docker is installed
  shell: |
    command -v docker >/dev/null 2>&1 || (echo "Docker missing" && exit 1)
  register: docker_check
  changed_when: false

- name: Ensure etcd data dir exists
  file:
    path: "{{ etcd_data_dir }}"
    state: directory
    owner: "{{ ansible_user | default('gpu-svc') }}"
    mode: '0755'
  become: true

- name: Run etcd container
  community.docker.docker_container:
    name: "{{ etcd_name }}"
    image: "{{ etcd_image }}"
    restart_policy: always
    state: started
    published_ports:
      - "{{ etcd_client_port }}:2379"
      - "{{ etcd_peer_port }}:2380"
    volumes:
      - "{{ etcd_data_dir }}:/etcd-data"
    environment:
      ETCDCTL_API: "3"
    command: >
      /usr/local/bin/etcd
        --name {{ etcd_name }}
        --data-dir /etcd-data
        {% if enable_tls %}
          --cert-file={{ etcd_cert_dir }}/etcd.pem
          --key-file={{ etcd_cert_dir }}/etcd-key.pem
          --trusted-ca-file={{ etcd_cert_dir }}/ca.pem
          --client-cert-auth=true
          --peer-cert-file={{ etcd_cert_dir }}/etcd.pem
          --peer-key-file={{ etcd_cert_dir }}/etcd-key.pem
          --peer-trusted-ca-file={{ etcd_cert_dir }}/ca.pem
          --peer-client-cert-auth=true
        {% endif %}
        --initial-advertise-peer-urls http://{{ etcd_ip }}:2380
        --listen-peer-urls http://0.0.0.0:2380
        --listen-client-urls http://0.0.0.0:2379
        --advertise-client-urls http://{{ etcd_ip }}:2379
        {% endif %}
        --initial-cluster-token {{ etcd_cluster_token }}
        --initial-cluster {{ initial_cluster }}
        --initial-cluster-state new
