{{- if and .Values.enabled (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rabbitmq.secretName" . }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.auth.existingSecretPasswordKey }}: {{ .Values.auth.password | quote }}
{{- end }}
