{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "rabbitmq.selectorLabels" . | nindent 4 }}
  ports:
    - name: amqp
      port: {{ .Values.service.port }}
      targetPort: amqp
      protocol: TCP
    - name: management
      port: {{ .Values.service.managementPort }}
      targetPort: management
      protocol: TCP
{{- end }}
